Add user mode

diff --git a/scripts/flexgettt b/scripts/flexgettt
--- a/scripts/flexgettt
+++ b/scripts/flexgettt
@@ -2,8 +2,8 @@
 # Author: Aniverse
 # https://github.com/Aniverse/aBox
 
-script_update=2020.03.19
-script_version=r10114
+script_update=2020.03.20
+script_version=r10115
 
 ########################################################################################################
 
@@ -14,10 +14,42 @@ rm -f /usr/local/bin/flexgettt ; nano /usr/local/bin/flexgettt ; chmod 755 /usr/
 
 ########################################################################################################
 
-config=/root/.config/flexget
+OPTS=$(getopt -o nlcxtis:u: --long "install,normal,log,cron,learn,test,log-backup,log-clean,search:,user:" -- "$@")
+eval set -- "$OPTS"
+[ ! $? = 0 ] && { echo -e "Invalid option: $1" ; mode=usage ; }
+
+while true; do
+  case "$1" in
+    -i  | --install   ) mode=install    ; shift ;;
+    -n  | --normal    ) mode=normal     ; shift ;;
+    -l  | --log       ) mode=show_log   ; shift ;;
+    -c  | --cron      ) mode=add2cron   ; shift ;;
+    -x  | --learn     ) mode=fg_learn   ; shift ;;
+    -t  | --test      ) mode=fg_test    ; shift ;;
+    --log-backup      ) mode=log_bak    ; shift ;;
+    --log-clean       ) mode=log_clean  ; shift ;;
+    -s  | --search    ) keyword="$2" ; mode=log_search ; shift 2 ;;
+    -u  | --user      ) iUser=$2        ; shift 2 ;;
+#   -- ) shift; break ;;
+    *  ) break ;;
+  esac
+done
+
+[[ -z $mode ]] && mode=usage
+
+[[ -z $iUser ]] && iUser=$(cat /log/inexistence/version | grep inexistence.user | awk '{print $NF}' | head -1)
+id -u $iUser >/dev/null 2>&1 || { echo -e "ERROR: User $iUser doesn't exist" ; exit 1 ; }
+[[ -z $iHome ]] && [[ $iUser == root ]] && iHome=/root
+[[ -z $iHome ]] && [[ $iUser != root ]] && iHome=/home/$iUser
+
+########################################################################################################
+
+config=$iHome/.config/flexget
+config_file=$iHome/.config/flexget/config.yml
+config_flag="-c $config_file"
 log=/log/script/check_flexget.log
 log_bak_path=/log/script/flexgettt
-flexget_log=/root/.config/flexget/flexget.log
+flexget_log=$iHome/.config/flexget/flexget.log
 flexget_cmd=/usr/local/bin/flexget
 
 user=$(whoami)
@@ -42,29 +74,7 @@ logs_rm_lock() { lines ; echo -e "$(date "+%Y-%m-%d %H:%M") ANIVERSE script DELE
 logs_rm_lock_color() { echo -e "${on_red}${bold}$(date "+%Y-%m-%d %H:%M") ANIVERSE script DELETED $config/.config-lock${normal}" ; }
 logs_execute() { lines ; echo -e "${on_cyan}${bold}$(date "+%Y-%m-%d %H:%M") ANIVERSE script execute${normal}" ; lines ; }
 
-########################################################################################################
 
-OPTS=$(getopt -o nlcxtis: --long "install,normal,log,cron,learn,test,log-backup,log-clean,search:" -- "$@")
-eval set -- "$OPTS"
-[ ! $? = 0 ] && { echo -e "Invalid option: $1" ; mode=usage ; }
-
-while true; do
-  case "$1" in
-    -i  | --install   ) mode=install    ; shift ;;
-    -n  | --normal    ) mode=normal     ; shift ;;
-    -l  | --log       ) mode=show_log   ; shift ;;
-    -c  | --cron      ) mode=add2cron   ; shift ;;
-    -x  | --learn     ) mode=fg_learn   ; shift ;;
-    -t  | --test      ) mode=fg_test    ; shift ;;
-    --log-backup      ) mode=log_bak    ; shift ;;
-    --log-clean       ) mode=log_clean  ; shift ;;
-    -s  | --search    ) keyword="$2" ; mode=log_search ; shift 2 ;;
-#   -- ) shift; break ;;
-    *  ) break ;;
-  esac
-done
-
-[[ -z $mode ]] && mode=usage
 
 ########################################################################################################
 
@@ -75,8 +85,8 @@ done
     logs_rm_lock >> $flexget_log
 }
 
-flexget_learn() { flexget execute --learn ; }
-flexget_test () { flexget  --test --loglevel debug execute ; }
+flexget_learn() { flexget $config_flag execute --learn ; }
+flexget_test () { flexget $config_flag --test --loglevel debug execute ; }
 
 install_script() {
     if [[ $EUID == 0 ]]; then
@@ -112,7 +122,7 @@ log_clean() {
 
 flexget_execute() {
     logs_execute >> $log
-    /usr/bin/time -f "Time used: %e" -a -o $log "$flexget_cmd" execute --no-cache 2>&1 >> $log
+    /usr/bin/time -f "Time used: %e" -a -o $log "$flexget_cmd" $config_flag execute --no-cache 2>&1 >> $log
 }
 
 flexget_add2cron() {
@@ -163,6 +173,7 @@ flexgettt $script_update $script_version
                 echo -n > /log/script/check_flexget.log
 -s              search log $1, eg.
                 flexgettt -s 23:33
+-u              specify user for flexget
 "
 }
 
